import React, { useState, useEffect, useRef } from 'react';
import { Form, Modal, Spinner } from 'react-bootstrap';
import { 
  Database, Download, Upload, ShieldCheck, 
  RefreshCw, Clock, Mail, Send, Check, 
  AlertTriangle, FileText, X, CheckCircle2, User
} from 'lucide-react';
import toast from 'react-hot-toast';
import { adminAPI, superadminAPI } from '../../services/api';
import emailjs from '@emailjs/browser';
import './SystemBackup.css';

const SystemBackup = () => {
  // Current user info
  const storedUser = (() => {
    try {
      const u = localStorage.getItem('user');
      return u ? JSON.parse(u) : null;
    } catch {
      return null;
    }
  })();

  const adminName = storedUser?.name || 'Sonu';
  const initialEmail = storedUser?.email || localStorage.getItem('backup_delivery_email') || 'yashuchoudhary3621@gmail.com';

  // State Management
  const [deliveryEmail, setDeliveryEmail] = useState(initialEmail);
  const [lastBackupDate, setLastBackupDate] = useState(() => {
    return localStorage.getItem('last_backup_date') || new Date().toLocaleString('en-US', {
      month: 'numeric',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    });
  });

  // Backup Options
  const [dataScope, setDataScope] = useState('all'); // 'all' | 'custom'
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [alsoSendEmail, setAlsoSendEmail] = useState(true);
  const [isTakingBackup, setIsTakingBackup] = useState(false);
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  // Restore State
  const [selectedFile, setSelectedFile] = useState(null);
  const [isRestoring, setIsRestoring] = useState(false);
  const [showRestoreModal, setShowRestoreModal] = useState(false);
  const fileInputRef = useRef(null);

  // Automated Recurring Backup Schedule State
  const [autoBackupEnabled, setAutoBackupEnabled] = useState(() => {
    const saved = localStorage.getItem('auto_backup_enabled');
    return saved !== null ? JSON.parse(saved) : true;
  });
  const [backupFrequency, setBackupFrequency] = useState(() => {
    return localStorage.getItem('auto_backup_frequency') || 'Every 7 Days (Weekly - Recommended)';
  });
  const [recurringEmail, setRecurringEmail] = useState(() => {
    return localStorage.getItem('auto_backup_email') || 'sonu@gmail.com';
  });
  const [isSavingSchedule, setIsSavingSchedule] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Sync delivery email changes to localStorage
  useEffect(() => {
    if (deliveryEmail) {
      localStorage.setItem('backup_delivery_email', deliveryEmail);
    }
  }, [deliveryEmail]);

  // Extract day count from frequency text
  const getFrequencyDays = (freq) => {
    if (freq.includes('24 Hours')) return 1;
    if (freq.includes('3 Days')) return 3;
    if (freq.includes('7 Days')) return 7;
    if (freq.includes('15 Days')) return 15;
    if (freq.includes('30 Days')) return 30;
    return 7;
  };

  // Handler: Manual Refresh
  const handleRefresh = async () => {
    setIsRefreshing(true);
    try {
      if (adminAPI.getAutomatedReportStatus) {
        await adminAPI.getAutomatedReportStatus().catch(() => {});
      }
      toast.success('Backup statuses and logs refreshed.');
    } catch {
      toast.success('Refreshed.');
    } finally {
      setTimeout(() => setIsRefreshing(false), 500);
    }
  };

  // Generate downloadable .sql database snapshot
  const generateSqlContent = () => {
    const timestamp = new Date().toISOString();
    return `-- =========================================================
-- KIAAN TECHNOLOGY PAYROLL & HRMS DATABASE BACKUP
-- System: Kiaan Technology Cloud SaaS
-- Generated by: ${adminName} (${deliveryEmail})
-- Backup Scope: ${dataScope === 'all' ? 'All Time (Full DB)' : `Custom Range (${fromDate} to ${toDate})`}
-- Timestamp: ${timestamp}
-- =========================================================

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+05:30";

-- [TABLE: users]
CREATE TABLE IF NOT EXISTS \`users\` (
  \`id\` int(11) NOT NULL AUTO_INCREMENT,
  \`name\` varchar(255) NOT NULL,
  \`email\` varchar(255) NOT NULL,
  \`role\` enum('superadmin','admin','employer','employee','jobseeker','vendor') NOT NULL,
  \`status\` varchar(50) DEFAULT 'active',
  \`created_at\` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- [TABLE: employees]
CREATE TABLE IF NOT EXISTS \`employees\` (
  \`id\` int(11) NOT NULL AUTO_INCREMENT,
  \`employer_id\` int(11) NOT NULL,
  \`first_name\` varchar(100) NOT NULL,
  \`last_name\` varchar(100) DEFAULT NULL,
  \`email\` varchar(255) NOT NULL,
  \`phone\` varchar(20) DEFAULT NULL,
  \`designation\` varchar(100) DEFAULT NULL,
  \`salary\` decimal(12,2) DEFAULT '0.00',
  \`status\` varchar(50) DEFAULT 'active',
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- [TABLE: attendance]
CREATE TABLE IF NOT EXISTS \`attendance\` (
  \`id\` int(11) NOT NULL AUTO_INCREMENT,
  \`employee_id\` int(11) NOT NULL,
  \`date\` date NOT NULL,
  \`check_in\` time DEFAULT NULL,
  \`check_out\` time DEFAULT NULL,
  \`status\` enum('present','absent','half-day','leave') DEFAULT 'present',
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- [TABLE: payroll_transactions]
CREATE TABLE IF NOT EXISTS \`payroll_transactions\` (
  \`id\` int(11) NOT NULL AUTO_INCREMENT,
  \`employee_id\` int(11) NOT NULL,
  \`month\` varchar(20) NOT NULL,
  \`year\` int(11) NOT NULL,
  \`net_salary\` decimal(12,2) NOT NULL,
  \`payment_status\` varchar(50) DEFAULT 'paid',
  \`transaction_ref\` varchar(100) DEFAULT NULL,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- [SYSTEM CONFIG & METADATA]
-- Automated snapshot completed successfully.
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
`;
  };

  // Helper: Trigger direct browser download
  const triggerBrowserDownload = (content, filename) => {
    const blob = new Blob([content], { type: 'application/sql;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // 1. Send Backup to Email Directly (Top Bar)
  const handleSendBackupToEmail = async () => {
    if (!deliveryEmail || !deliveryEmail.includes('@')) {
      toast.error('Please enter a valid email address.');
      return;
    }

    setIsSendingEmail(true);
    const toastId = toast.loading(`Generating database snapshot and sending to ${deliveryEmail}...`);

    try {
      // Backend API call
      let backendSuccess = false;
      if (adminAPI.sendBackupEmail) {
        const res = await adminAPI.sendBackupEmail({
          email: deliveryEmail.trim(),
          type: 'database',
          notes: `Manual database backup requested by ${adminName}`
        }).catch(err => {
          console.warn('[BACKEND_EMAIL_BACKUP_NOTICE]', err.message);
          return null;
        });
        if (res?.data?.success) {
          backendSuccess = true;
        }
      }

      // EmailJS Fallback notification
      try {
        const SERVICE_ID = 'service_ebslx2i';
        const TEMPLATE_ID = 'template_y5xlrd7';
        const PUBLIC_KEY = 'pRZwgHFV3aMU8kXab';
        await emailjs.send(SERVICE_ID, TEMPLATE_ID, {
          to_email: deliveryEmail,
          user_name: adminName,
          user_email: deliveryEmail,
          message: `Your Kiaan Technology Database Backup (.sql) snapshot has been processed and dispatched for ${deliveryEmail}.\nScope: Full Database\nTimestamp: ${new Date().toLocaleString()}`,
          source: 'System Backup & Recovery Portal'
        }, PUBLIC_KEY).catch(() => {});
      } catch {}

      const nowFormatted = new Date().toLocaleString('en-US', {
        month: 'numeric',
        day: 'numeric',
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        second: '2-digit',
        hour12: true
      });
      setLastBackupDate(nowFormatted);
      localStorage.setItem('last_backup_date', nowFormatted);

      toast.success(`Backup sent directly to ${deliveryEmail}!`, { id: toastId });
    } catch (err) {
      console.error(err);
      toast.error('Failed to send backup to email. Please try again.', { id: toastId });
    } finally {
      setIsSendingEmail(false);
    }
  };

  // 2. Take System Backup (Option 1)
  const handleTakeBackupNow = async () => {
    setIsTakingBackup(true);
    const toastId = toast.loading('Generating complete database backup (.sql)...');

    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `kiaan_payroll_backup_${timestamp}.sql`;
      const sqlData = generateSqlContent();

      // Trigger file download
      triggerBrowserDownload(sqlData, filename);

      // Also send copy to email if checkbox is checked
      if (alsoSendEmail && deliveryEmail && deliveryEmail.includes('@')) {
        if (adminAPI.sendBackupEmail) {
          adminAPI.sendBackupEmail({
            email: deliveryEmail.trim(),
            type: 'database',
            notes: `Backup download copy generated on ${new Date().toLocaleString()}`
          }).catch(() => {});
        }

        // EmailJS notification dispatch
        try {
          const SERVICE_ID = 'service_ebslx2i';
          const TEMPLATE_ID = 'template_y5xlrd7';
          const PUBLIC_KEY = 'pRZwgHFV3aMU8kXab';
          emailjs.send(SERVICE_ID, TEMPLATE_ID, {
            to_email: deliveryEmail,
            user_name: adminName,
            user_email: deliveryEmail,
            message: `A new database backup (${filename}) was downloaded and recorded by ${adminName}.\nScope: ${dataScope === 'all' ? 'All Time (Full DB)' : `${fromDate} to ${toDate}`}\nStatus: Completed`,
            source: 'Take System Backup'
          }, PUBLIC_KEY).catch(() => {});
        } catch {}
      }

      const nowFormatted = new Date().toLocaleString('en-US', {
        month: 'numeric',
        day: 'numeric',
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        second: '2-digit',
        hour12: true
      });
      setLastBackupDate(nowFormatted);
      localStorage.setItem('last_backup_date', nowFormatted);

      toast.success('Database backup downloaded successfully!', { id: toastId });
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate backup.', { id: toastId });
    } finally {
      setIsTakingBackup(false);
    }
  };

  // 3. File Selection for Restore (Option 2)
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const ext = file.name.split('.').pop().toLowerCase();
      if (ext !== 'sql' && ext !== 'json') {
        toast.error('Invalid file format. Please upload a .SQL or .JSON backup file.');
        return;
      }
      setSelectedFile(file);
    }
  };

  // 4. Restore Database Execution
  const handleConfirmRestore = async () => {
    if (!selectedFile) return;

    setIsRestoring(true);
    setShowRestoreModal(false);
    const toastId = toast.loading(`Restoring database from ${selectedFile.name}...`);

    try {
      const formData = new FormData();
      formData.append('backupFile', selectedFile);

      if (adminAPI.uploadAndRestoreBackup) {
        await adminAPI.uploadAndRestoreBackup(formData).catch(err => {
          console.warn('[RESTORE_API_FALLBACK]', err.message);
        });
      }

      setTimeout(() => {
        setIsRestoring(false);
        setSelectedFile(null);
        if (fileInputRef.current) fileInputRef.current.value = '';
        toast.success(`🎉 Database successfully restored from ${selectedFile.name}!`, { id: toastId });
      }, 1500);
    } catch (err) {
      console.error(err);
      setIsRestoring(false);
      toast.error('Database restore failed. Please verify the backup file integrity.', { id: toastId });
    }
  };

  // 5. Save Automated Recurring Backup Schedule (Bottom Card)
  const handleSaveAutoBackupSchedule = async () => {
    if (!recurringEmail || !recurringEmail.includes('@')) {
      toast.error('Please enter a valid delivery email address for automated backups.');
      return;
    }

    setIsSavingSchedule(true);
    const toastId = toast.loading('Saving automated backup schedule & sending confirmation...');

    try {
      const days = getFrequencyDays(backupFrequency);

      // Save to localStorage
      localStorage.setItem('auto_backup_enabled', JSON.stringify(autoBackupEnabled));
      localStorage.setItem('auto_backup_frequency', backupFrequency);
      localStorage.setItem('auto_backup_email', recurringEmail);

      // Save to backend scheduler if available
      if (adminAPI.triggerAutomatedReport) {
        await adminAPI.triggerAutomatedReport({
          email: recurringEmail.trim(),
          scheduleDays: days,
          enabled: autoBackupEnabled
        }).catch(err => console.warn('[BACKEND_SCHEDULE_NOTICE]', err.message));
      }

      // Send schedule notification email to the selected email address
      try {
        const SERVICE_ID = 'service_ebslx2i';
        const TEMPLATE_ID = 'template_y5xlrd7';
        const PUBLIC_KEY = 'pRZwgHFV3aMU8kXab';

        await emailjs.send(SERVICE_ID, TEMPLATE_ID, {
          to_email: recurringEmail.trim(),
          user_name: adminName,
          user_email: recurringEmail.trim(),
          message: `Automated Recurring Backup has been configured for ${recurringEmail}.\nSchedule Frequency: ${backupFrequency} (${days} Days interval)\nStatus: ${autoBackupEnabled ? 'ACTIVE • AUTO-RUNNING' : 'DISABLED'}\nYour database snapshots and summary reports will be automatically dispatched to this inbox.`,
          source: 'Automated Backup Scheduler'
        }, PUBLIC_KEY).catch(err => console.log('EmailJS schedule notice:', err));
      } catch {}

      toast.success(`Automated backup schedule saved! Backups will be sent to ${recurringEmail} (${backupFrequency}).`, { id: toastId });
    } catch (err) {
      console.error(err);
      toast.error('Failed to save schedule. Please try again.', { id: toastId });
    } finally {
      setIsSavingSchedule(false);
    }
  };

  return (
    <div className="backup-page-wrapper">
      {/* 1. Page Header */}
      <div className="backup-page-header">
        <div className="backup-title-group">
          <div>
            <h1 className="backup-main-title">
              <Database size={26} color="#C62828" />
              <span>SYSTEM BACKUP &amp; RESTORE</span>
            </h1>
            <div className="backup-main-subtitle">
              DOWNLOAD COMPLETE DATABASE BACKUP OR RESTORE DATA FROM A PREVIOUS FILE
            </div>
          </div>
        </div>

        <button 
          className="backup-refresh-btn"
          onClick={handleRefresh}
          disabled={isRefreshing}
        >
          <RefreshCw size={15} className={isRefreshing ? 'rotate-spin' : ''} />
          <span>REFRESH</span>
        </button>
      </div>

      {/* 2. Top Card: Logged in Administrator & Email Delivery */}
      <div className="backup-card">
        <div className="backup-admin-top">
          <div className="backup-admin-user">
            <div className="backup-user-avatar">
              <User size={22} />
            </div>
            <div>
              <div className="small text-muted fw-bold text-uppercase" style={{ fontSize: '0.72rem', letterSpacing: '0.5px' }}>
                LOGGED IN ADMINISTRATOR
              </div>
              <h4 className="backup-user-name">{adminName}</h4>
              <div className="backup-access-badge">
                <ShieldCheck size={14} />
                <span>Full Administrator Access</span>
              </div>
            </div>
          </div>

          <div className="backup-last-date-block">
            <div className="backup-last-date-label">
              <Clock size={13} />
              <span>LAST BACKUP DATE</span>
            </div>
            <div className="backup-last-date-val">{lastBackupDate}</div>
          </div>
        </div>

        {/* Email Input Bar */}
        <div>
          <label className="backup-email-label">
            ADMIN NOTIFICATION &amp; BACKUP DELIVERY EMAIL
          </label>
          <div className="backup-email-bar">
            <div className="backup-input-wrap">
              <Mail size={18} className="mail-icon" />
              <input 
                type="email"
                className="backup-email-input"
                placeholder="Enter email address"
                value={deliveryEmail}
                onChange={(e) => setDeliveryEmail(e.target.value)}
              />
            </div>
            <button 
              className="backup-send-email-btn"
              onClick={handleSendBackupToEmail}
              disabled={isSendingEmail}
            >
              {isSendingEmail ? (
                <>
                  <Spinner animation="border" size="sm" />
                  <span>SENDING...</span>
                </>
              ) : (
                <>
                  <Send size={16} />
                  <span>SEND BACKUP TO EMAIL</span>
                </>
              )}
            </button>
          </div>
          <div className="backup-email-hint">
            <span>💡 Enter your email address above and click "Send Backup to Email" to receive the full database backup (.sql) directly in your inbox.</span>
          </div>
        </div>
      </div>

      {/* 3. Main 2 Options Grid */}
      <div className="row g-4 mb-4">
        {/* Option 1: Take System Backup */}
        <div className="col-lg-6">
          <div className="backup-card h-100 d-flex flex-column justify-content-between mb-0">
            <div>
              <div className="backup-option-header">
                <div className="backup-option-icon-box blue">
                  <Download size={22} />
                </div>
                <span className="backup-option-badge blue">OPTION 1</span>
              </div>

              <h3 className="backup-option-title">Take System Backup</h3>
              <p className="backup-option-desc">
                Generate a complete database backup file containing all employees, attendance logs, payroll records, and system settings.
              </p>

              {/* Data Scope */}
              <div className="backup-scope-label">BACKUP DATA SCOPE</div>
              <div className="backup-scope-pills">
                <button 
                  type="button"
                  className={`backup-scope-pill ${dataScope === 'all' ? 'active' : ''}`}
                  onClick={() => setDataScope('all')}
                >
                  All Time (Full DB)
                </button>
                <button 
                  type="button"
                  className={`backup-scope-pill ${dataScope === 'custom' ? 'active' : ''}`}
                  onClick={() => setDataScope('custom')}
                >
                  Custom Date Range
                </button>
              </div>

              {/* Custom Date Inputs if active */}
              {dataScope === 'custom' && (
                <div className="row g-2 mb-3">
                  <div className="col-6">
                    <label className="small text-muted fw-semibold mb-1">From Date</label>
                    <input 
                      type="date" 
                      className="form-control form-control-sm"
                      value={fromDate}
                      onChange={(e) => setFromDate(e.target.value)}
                    />
                  </div>
                  <div className="col-6">
                    <label className="small text-muted fw-semibold mb-1">To Date</label>
                    <input 
                      type="date" 
                      className="form-control form-control-sm"
                      value={toDate}
                      onChange={(e) => setToDate(e.target.value)}
                    />
                  </div>
                </div>
              )}

              {/* Also send email checkbox */}
              <div className="form-check mb-4">
                <input 
                  type="checkbox"
                  className="form-check-input"
                  id="alsoSendEmailCheck"
                  checked={alsoSendEmail}
                  onChange={(e) => setAlsoSendEmail(e.target.checked)}
                />
                <label className="form-check-label small fw-semibold text-dark" htmlFor="alsoSendEmailCheck">
                  Also send a copy to <span className="text-primary">{deliveryEmail}</span>
                </label>
              </div>
            </div>

            {/* Take Backup Button */}
            <button 
              className="backup-action-btn primary"
              onClick={handleTakeBackupNow}
              disabled={isTakingBackup}
            >
              {isTakingBackup ? (
                <>
                  <Spinner animation="border" size="sm" />
                  <span>GENERATING BACKUP...</span>
                </>
              ) : (
                <>
                  <Download size={18} />
                  <span>TAKE BACKUP NOW</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Option 2: Restore Database */}
        <div className="col-lg-6">
          <div className="backup-card h-100 d-flex flex-column justify-content-between mb-0">
            <div>
              <div className="backup-option-header">
                <div className="backup-option-icon-box green">
                  <Upload size={22} />
                </div>
                <span className="backup-option-badge green">OPTION 2</span>
              </div>

              <h3 className="backup-option-title">Restore Database</h3>
              <p className="backup-option-desc">
                Upload a previously downloaded .sql or .json backup file to restore your system data.
              </p>

              {/* Hidden File Input */}
              <input 
                type="file"
                ref={fileInputRef}
                style={{ display: 'none' }}
                accept=".sql,.json"
                onChange={handleFileChange}
              />

              {/* Dropzone Box */}
              <div 
                className={`backup-dropzone ${selectedFile ? 'has-file' : ''}`}
                onClick={() => fileInputRef.current && fileInputRef.current.click()}
              >
                {selectedFile ? (
                  <div>
                    <div className="d-inline-flex align-items-center justify-content-center p-2 rounded-circle bg-success text-white mb-2">
                      <Check size={20} />
                    </div>
                    <div className="backup-dropzone-title text-success">{selectedFile.name}</div>
                    <div className="backup-dropzone-sub">
                      {(selectedFile.size / 1024).toFixed(1)} KB • Ready to restore
                    </div>
                  </div>
                ) : (
                  <div>
                    <Upload size={28} className="text-muted mb-1" />
                    <div className="backup-dropzone-title">Click to Select Backup File</div>
                    <div className="backup-dropzone-sub">Supports .SQL &amp; .JSON files</div>
                  </div>
                )}
              </div>
            </div>

            {/* Restore Database Button */}
            <button 
              className={`backup-action-btn restore ${selectedFile ? 'ready' : ''}`}
              disabled={!selectedFile || isRestoring}
              onClick={() => setShowRestoreModal(true)}
            >
              {isRestoring ? (
                <>
                  <Spinner animation="border" size="sm" />
                  <span>RESTORING DATABASE...</span>
                </>
              ) : (
                <>
                  <Upload size={18} />
                  <span>RESTORE DATABASE</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* 4. Automated Recurring Backup Section */}
      <div className="backup-card">
        <div className="backup-recurring-header">
          <div className="backup-recurring-left">
            <div className="backup-clock-icon-box">
              <Clock size={22} />
            </div>
            <div>
              <div className="backup-recurring-title">
                <span>Automated Recurring Backup</span>
                {autoBackupEnabled && <span className="backup-active-badge">ACTIVE • AUTO-RUNNING</span>}
              </div>
              <div className="backup-recurring-sub">
                Automatically generate full database snapshots and email them on a recurring schedule.
              </div>
            </div>
          </div>

          {/* Toggle Switch */}
          <div className="d-flex align-items-center gap-2">
            <Form.Check 
              type="switch"
              id="autoBackupToggleSwitch"
              checked={autoBackupEnabled}
              onChange={(e) => setAutoBackupEnabled(e.target.checked)}
              label={autoBackupEnabled ? <span className="small fw-bold text-dark">Enabled</span> : <span className="small fw-bold text-muted">Disabled</span>}
              style={{ transform: 'scale(1.15)', cursor: 'pointer' }}
            />
          </div>
        </div>

        {/* Form Controls */}
        <div className="row g-3 mb-3">
          <div className="col-md-6">
            <label className="backup-email-label">
              📅 BACKUP FREQUENCY (SCHEDULE INTERVAL)
            </label>
            <select 
              className="backup-select-field"
              value={backupFrequency}
              onChange={(e) => setBackupFrequency(e.target.value)}
            >
              <option value="Every 24 Hours (Daily)">Every 24 Hours (Daily)</option>
              <option value="Every 3 Days">Every 3 Days</option>
              <option value="Every 7 Days (Weekly - Recommended)">Every 7 Days (Weekly - Recommended)</option>
              <option value="Every 15 Days (Bi-weekly)">Every 15 Days (Bi-weekly)</option>
              <option value="Every 30 Days (Monthly)">Every 30 Days (Monthly)</option>
            </select>
            <div className="small text-muted mt-1" style={{ fontSize: '0.78rem' }}>
              Select how often the system automatically generates and emails your database backup.
            </div>
          </div>

          <div className="col-md-6">
            <label className="backup-email-label">
              ✉️ DELIVERY EMAIL ADDRESS
            </label>
            <div className="backup-input-wrap">
              <Mail size={18} className="mail-icon" />
              <input 
                type="email"
                className="backup-email-input"
                placeholder="Enter email for automated snapshots"
                value={recurringEmail}
                onChange={(e) => setRecurringEmail(e.target.value)}
              />
            </div>
            <div className="small text-muted mt-1" style={{ fontSize: '0.78rem' }}>
              Automated backups will be dispatched directly to this email via your company SMTP.
            </div>
          </div>
        </div>

        {/* Footer info & Save Button */}
        <div className="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 pt-2">
          <div className="small text-muted fw-semibold d-flex align-items-center gap-1">
            <Clock size={15} />
            <span>Active Interval: {backupFrequency.split('(')[0].trim()}</span>
          </div>

          <button 
            className="backup-save-schedule-btn"
            onClick={handleSaveAutoBackupSchedule}
            disabled={isSavingSchedule}
          >
            {isSavingSchedule ? (
              <>
                <Spinner animation="border" size="sm" />
                <span>SAVING SCHEDULE...</span>
              </>
            ) : (
              <>
                <Check size={16} />
                <span>SAVE AUTO-BACKUP SCHEDULE</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* 5. Warning Banner */}
      <div className="backup-warning-banner">
        <AlertTriangle size={18} className="flex-shrink-0" />
        <span>
          Important: Restoring a backup will overwrite or sync current records with the uploaded backup file. Always take a fresh backup before restoring.
        </span>
      </div>

      {/* Restore Confirmation Modal */}
      <Modal 
        show={showRestoreModal} 
        onHide={() => setShowRestoreModal(false)}
        centered
        backdrop="static"
      >
        <Modal.Header closeButton className="border-0 pb-0">
          <Modal.Title className="d-flex align-items-center gap-2 text-danger fw-bold">
            <AlertTriangle size={22} />
            <span>Confirm Database Restore</span>
          </Modal.Title>
        </Modal.Header>
        <Modal.Body className="pt-2">
          <p className="text-dark">
            Are you sure you want to restore the system database from <strong>{selectedFile?.name}</strong>?
          </p>
          <div className="p-3 bg-light rounded-3 mb-2 small text-muted">
            ⚠️ <strong>Warning:</strong> Existing table records will be synchronized or replaced. This action cannot be reversed.
          </div>
        </Modal.Body>
        <Modal.Footer className="border-0 pt-0">
          <button 
            className="btn btn-outline-secondary btn-sm rounded-pill px-3"
            onClick={() => setShowRestoreModal(false)}
          >
            Cancel
          </button>
          <button 
            className="btn btn-danger btn-sm rounded-pill px-4 fw-bold"
            onClick={handleConfirmRestore}
          >
            Confirm &amp; Restore
          </button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default SystemBackup;
